cc_test(
    name = "tests",
    srcs = [
        "greeting_test.cc",
    ],
    deps = [
        "//src:serverLib",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "redis_test",
    srcs = [
        "redis_manager_test.cc",
    ],
    deps = [
        "//src:serverLib",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "db_test",
    srcs = ["db_test.cc"],
    deps = [
        "//src:serverLib",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "user_dao_test",
    srcs = ["user_dao_test.cc"],
    deps = [
        "//src:serverLib",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "token_manager_test",
    srcs = ["token_manager_test.cc"],
    deps = [
        "//src:serverLib",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "crypto_manager_test",
    srcs = ["crypto_manager_test.cc"],
    deps = [
        "//src:serverLib",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "product_dao_test",
    srcs = ["product_dao_test.cc"],
    deps = [
        "//src:serverLib",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "arrangement_dao_test",
    srcs = ["arrangement_dao_test.cc"],
    deps = [
        "//src:serverLib",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "identification_dao_test",
    srcs = ["identification_dao_test.cc"],
    deps = [
        "//src:serverLib",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "user_facade_test",
    srcs = ["user_facade_test.cc"],
    deps = [
        "//src:serverLib",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "snowflake_id_manager_test",
    srcs = ["snowflake_id_manager.cc"],
    deps = [
        "//src:serverLib",
        "@googletest//:gtest_main",
    ],
)
