name: CI

on:
  push: {}

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1

    - name: Build
      uses: ngalaiko/bazel-action/2.0.0@master
      with:
        args: build //...

    - name: Start Redis
      uses: supercharge/redis-github-action@1.1.0
      with:
        redis-version: 5
    
    - name: Setup Runner Database
      run: |
        sudo systemctl start mysql
        mysql -uroot -h127.0.0.1 -proot < ./conf/create_table.sql

    - name: Test
      uses: ngalaiko/bazel-action/2.0.0@master
      with:
        args: test //... --test_env=mysql_user=root --test_env=mysql_password=root --test_env=mysql_database=fcdeduction --test_env=salt=123456