name: CI

on:
  push: {}

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mysql:5.7
        ports:
          - 3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: fcdeduction
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
    - uses: actions/checkout@v1

    - name: Mount bazel cache
      uses: actions/cache@v1
      with:
        path: "/home/runner/.cache/bazel"
        key: bazel

    - name: Install bazelisk
      run: |
        curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.1.0/bazelisk-linux-amd64"
        mkdir -p "${GITHUB_WORKSPACE}/bin/"
        mv bazelisk-linux-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
        chmod +x "${GITHUB_WORKSPACE}/bin/bazel"

    - name: Build
      run: |
        "${GITHUB_WORKSPACE}/bin/bazel" build $(${GITHUB_WORKSPACE}/bin/bazel query //...) --copt -DGRPC_BAZEL_BUILD

    - name: Start Redis
      uses: supercharge/redis-github-action@1.1.0
      with:
        redis-version: 5
    
    - name: Verify MySQL connection from container 
      run: |
        apt-get update
        apt-get install -y mysql-client
        mysql ---user=${{secrets.mysql_user}} --password=${{secrets.mysql_password}}  -e "SHOW DATABASES"
    
    - name: Create tabele 
      run: |
        mysql --user=${{secrets.mysql_user}} --database=${{secrets.mysql_database }} --password=${{secrets.mysql_password}} < ./conf/create_table.sql

    - name: Test
      run: |
        "${GITHUB_WORKSPACE}/bin/bazel" test $("${GITHUB_WORKSPACE}/bin/bazel" query //...) --copt -DGRPC_BAZEL_BUILD --test_env=mysql_user=${{secrets.mysql_user}}  --test_env=mysql_database=${{secrets.mysql_database }} --test_env=mysql_password=${{secrets.mysql_password}}
